# HyprIdle ist ein Programm in den Sparmodus zu aktivieren.
# Das Programm ist mir von Gemini gegeben worden und ist mit dem Standard INI und TOML geschrieben.  
# Toml ist eine Weiterentwicklung von INI, dafür muss aber genauer definiert werden.
# In TOML müssen im Gegensatz zu INI Strings mir "" gekennzeichnet werden.

general {
	lock_cmd = pidof hyprlock || hyprlock		# Befehl zum Sperren
	before_sleep_cmd = loginctl lock-session	# Sperren vor dem Standyby
	after_sleep_cmd = hyprctl dispatch dpms on	# Bildschirm an nach dem Aufwachen
}

listener {
	timeout = 180 					# 5 Minuten
	on-timeout = loginctl lock-session		# Bildschirm sperren
}

listener {
	timeout = 240					# 5,5 Minuten
	on-timeout = hyprctl dispatch dpms off		# Bildschirm ausschalten (Sparmodus)
	on-resume = hyprctl dispatch dpms on		# Bildschirm wieder ann bei Aktivität
}

listener {
	timeout = 300					# 10 Minuten
	on-timeout = systemctl suspend			# Rechner in den Standby schicken
